### ISSUE TITLE
Allow configuration via environment variables

### ISSUE THREAD

**Issue by brianredbeard** [Expensify/Bedrock#100]
In order to more easily use Bedrock in a containerized manner, it would be nice
to utilize configuration with environment variables.

  -versionOverride <version>
  -db             <filename>
  -serverHost     <host:port>
  -nodeName       <name>
  -nodeHost       <host:port>
  -peerList       <list>
  -priority       <value>
  -plugins        <list>
  -cacheSize      <kb>
  -readThreads    <#>
  -queryLog       <filename>
  -maxJournalSize <#commits>

For each of these it would seem that taking the form `BEDROCK_` followed by the
option name in all caps would follow, e.g.
`BEDROCK_DB=/var/lib/bedrock/bedrock.db` or `BEDROCK_READTHREADS=12`.

**Comment by quinthar** [comment]
Ah, that's an interesting approach.  I bet you could do that by just defining the environment variables and then referencing them on the command line.  That said, I actually prefer command-line configuration due to it showing all the parameters clearly in the process, which we've found *invaluable* for debugging.
