### ISSUE TITLE
Is compilation on OSX supported? 

### ISSUE THREAD

**Issue by mindreframer** [Expensify/Bedrock#120]
First, thx for the outstanding project, I wish it would get more exposure! 

On the YN thread here https://news.ycombinator.com/item?id=12739771 @quinthar says that most of the development happens on OSX.

![screen shot 2017-03-14 at 11 44 17](https://cloud.githubusercontent.com/assets/1232/23897163/53ce9870-08ac-11e7-9566-98bbe8e1e3cf.png)

After some fiddling around (gcc instead of gcc-6 and g++ instead of g++-6 for my system) the build breaks here: 

```
$ make all
g++ -O0 -g -std=gnu++11 -DSVERSION="\"954c75063b232bd3d39f56c81e2acce75d380a69\"" -Wall -I/private/tmp/Bedrock -I/private/tmp/Bedrock/mbedtls/include -MMD -MF .build/libstuff/STCPNode.d  -o .build/libstuff/STCPNode.o -c libstuff/STCPNode.cpp
libstuff/STCPNode.cpp:167:45: error: no matching function for call to 'max'
                            peer->latency = max(STimeNow() - message.calc64("Timestamp"), 1ul);
                                            ^~~
```

It would be great to have some instructions how to build bedrock directly on OSX (if it is already the used workflow for current development). 

[EDIT] I also had to init git submodules: 
```
$ git submodule init
$ git submodule update
```

**Comment by quinthar** [comment]
Hi Roman, thanks for asking.  We actually stopped supporting OSX builds
here at Expensify because we do all Bedrock developing inside Vagrant
Ubuntu VMs.  However, it'd be great if someone else were to step up to take
on that responsibility.  In this particular case, this link might be
helpful:
http://stackoverflow.com/questions/21821527/error-on-xcode-no-matching-function-for-call-to-max
 Thanks!

**Comment by mindreframer** [comment]
Hi David,

good to know! 

Just got it compiled, where should I document this?

**Comment by quinthar** [comment]
Perhaps submit a PR for the homepage at bedrockdb.com to give OSX build and
install instructions?
