### ISSUE TITLE
Replication / failover details?

### ISSUE THREAD

**Issue by coleifer** [Expensify/Bedrock#203]
I saw in the docs that this project uses paxos under-the-hood for leader election, but I was having a bit of trouble finding where in the code-base this is implemented. Could someone point me to the paxos impl?

**Comment by quinthar** [comment]
Hi!  Here's a link to some comments that outline the clustering algorithm:

https://github.com/Expensify/Bedrock/blob/master/sqlitecluster/SQLiteNode.cpp#L268

There is no "paxos" code block (the word doesn't even appear in the codebase, I don't think).  Rather, Paxos is just a good way to describe the clustering algorithm to elect a master.  Thanks for asking!

**Comment by coleifer** [comment]
Thanks, I missed that when I was looking around. I saw you all talking about multi-threaded writes, by the way, and wondered if you'd considered Oracle's SQLite front-end for BerkeleyDB? Whitepaper is here: http://www.oracle.com/technetwork/database/berkeleydb/learnmore/bdbvssqlite-wp-186779.pdf ... And the money-shot:

![s1496266716 23](https://cloud.githubusercontent.com/assets/119974/26655239/a8d558a8-461f-11e7-9d36-5fb3fa8a0f20.png)

BerkeleyDB / SQLite does page-level locking, *and* supports multi-version concurrency control, so I imagine it might be of interest to you.

There's also [rqlite](https://github.com/rqlite/rqlite), distributed sqlite using raft. It claims to be production-ready, though I can't vouch for it myself.

Oh, and of course [actordb](http://www.actordb.com/docs-howitworks.html#overview) -- another distributed sqlite take. I believe they're hijacking the WAL and using it to inject their own storage, which is kind of neat. https://github.com/biokoda/actordb_driver/blob/master/c_src/wal.c

Best of luck on the project!

**Comment by quinthar** [comment]
Ah, we've considered BDB as the concurrent writing with page locking is very attractive.  However, SQLite has since added concurrent writing with page locking (in a branch), so that's where we're starting first.  We've been *extremely* happy with SQLite's performance overall, and are optimistic with the early results of multiple writers.  In general, I think SQLite's and BDB's page locking is probably equivalent, but SQLite's has the advantage of being built right in.

I haven't checked out rqlite -- it sounds similar in concept to BedrockDB.  Given that we already have Bedrock and it's working great, I'm inclined to stick with it.

As for ActorDB, I also haven't checked it out, but this line alarms me:

> ActorDB is a relational SQL database, but it requires a different way of organizing your data. 

I think if we can get solid write concurrency on the master, then even if the master is the bottleneck, we should be fine for another order of magnitude or two.  After that, who knows!

**Comment by coleifer** [comment]
That's interesting about SQLite supporting multiple writers / finer-grained locking, I sparingly follow the mailing list but I'll keep an eye out for more news on it.

Love seeing all the cool ways people are using SQLite. I'll keep an eye on this project :)
