### ISSUE TITLE
The chickens and the eggs

### ISSUE THREAD

**Issue by Crazee** [Expensify/Bedrock#256]
So I was trying to set up a cluster that could “grow” over time — didn’t know all the IP addresses in advance so would start 1 node, then the second would contact the 1st, and the third would contact the 1st and 2nd, etc.

Well, **bedrock** didn’t like that at all: "Incoming connection failed from … (unauthenticated node) …”.  Seems to only want a static list of nodes known at the beginning of time.

So I “fixed” _STCPNode.cpp_ to accept new nodes (it’s safe on my secure overlay network) with an extra **addPeer()** call and that works for me.  I also tried to add a command-line flag to enable/disable this feature but ran into the police-state c++ behavior of having locked up the command “args”, incommunicado, in some object where you couldn’t get at them from where you need them.  So no user-friendly command option.

**Comment by quinthar** [comment]
Ah, this is not supported for a reason: each node needs to know how many
other nodes are in the cluster in order to know when half of the cluster is
connected for quorum purposes.  If you allow dynamic node additions, it
opens up the possibility of the cluster "forking" into two halves that each
think they have more than half (and thus, each thinking it has quorum).
This is the "split brain" scenario that is about the worst possible
nightmare to avoid.

**Comment by Crazee** [comment]
I was trying to test a couple of use cases:

1.  Start with a cluster of 3 nodes; run for some time;  grow the cluster to 5 nodes in two more locations.

2. Have a cluster of 3 nodes.  Take one down and move it to a different datacenter/provider with a different IP address.

Can this be done with no downtime?

**Comment by quinthar** [comment]
Hmmm I don't think we've ever tried that.  I imagine I could be done with
enough care and restarts, but it's not something we've designed for.  We
run with 6 nodes and just upgrade in place as needed, so we haven't really
needed zero-downtime cluster reconfiguration, but it's an interesting
idea!  Are you solving some specific problem or just sorta kicking the
tires?

**Comment by Crazee** [comment]
Trying to figure out the "suitability" of Bedrock to what we do in our application -- so, "kicking the tires" would be about right.  We run bits in datacenters around the world and may be using Kubernetes to orchestrate things, and it likes to pick bits up and move them around.  Although many bits move from one place to another (say when one provider is under DDOS attack) the database is stuck in one datacenter.  Looking to find a solution that provides a bit more reliability.

**Comment by quinthar** [comment]
Hm, well Bedrock is very explicitly designed for a WAN-replicated
environment across different datacenters, so that sounds like it could be
good.  However, it's not really designed to be moved around easily.

In our experience, it works best to just configure it to work in as many
datacenters as you have, and then balance all traffic equally across them
all (or use anycast to route users to the nearest datacenter).  If a
datacenter fails for any reason, rather than frantically spinning up a new
datacenter, just allow the traffic to automatically route to the others
that are already in place.  However, it sounds like you might have slightly
different requirements: is there a reason that you prefer to move instances
frequently and in a hurry between different datacenters?  How big are the
databases you are dealing with?  In our case it takes many hours to
download a backup and such, so there isn't really any way to spin up
anything fast, hence the pre-positioning of adequate resources to weather
the storm.

We think three datacenters is the magic number, but that also means that
we're 50% over-provisioned for peak.  I can imagine running that closer to
the edge to optimize cost, but that's not a scenario we've really optimized
for.

**Comment by wmertens** [comment]
So basically, if the number of peers is configured beforehand, and you're allowed to dynamically remove and add peers up to that number, and you never go below `n/2`, it is fine?

**Comment by quinthar** [comment]
Lmk if you need anything else on this, otherwise closing it!
