### ISSUE TITLE
Clarify, if the solution can run on MS Windows

### ISSUE THREAD

**Issue by vlcinsky** [Expensify/Bedrock#66]
I did not find a note about possible compatibility of bedrock with MS Windows (none, possible, planned, implemented).

For some use cases would MS Windows implementation help.

**Comment by quinthar** [comment]
Hi!  Most of the original `libstuff` code was originally written to be Windows compatible, but we haven't built against it in years so that code was removed.  That said, there are very few places that are platform specific, so I don't think a Windows (re)port would be difficult.  So, PRs welcome!  However, this isn't something that Expensify is currently developing.  Thanks for asking!
